// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	NEXT_PUBLIC_TURNSTILE_SITE_KEY: "0x4AAAAAAB0WQ2FQJxf6OelG";
	NEXT_PUBLIC_JWT_ISSUER: "https://jwtworker.gprotocol.dev/api/v1/validate-turnstile";
	NEXT_PUBLIC_HASURA_HTTP_ENDPOINT: "http://localhost:8080/v1/graphql";
	NEXT_PUBLIC_HASURA_WS_ENDPOINT: "ws://localhost:8080/v1/graphql";
	NEXT_PUBLIC_APP_ADDRESS: "0x4b2a5d86144410a66d6e5914bf833074b8cba028";
	NEXT_PUBLIC_TOKEN_ADDRESS: "0x0aa35F27544B998678b94285D9D51A6d8214BD77";
}
